config/routes.rb
Rails.application.routes.draw do








  # get 'vendor_contracts/_form'
  #
  # get 'vendor_contracts/edit'
  #
  # get 'vendor_contracts/index'
  #
  # get 'vendor_contracts/new'
  #
  # get 'vendor_contracts/show'
  #
  # get 'vendors/_form'
  #
  # get 'vendors/edit'
  #
  # get 'vendors/index'
  #
  # get 'vendors/new'
  #
  # get 'vendors/show'
  #
  # get 'vendor_types/_form'
  #
  # get 'vendor_types/edit'
  #
  # get 'vendor_types/index'
  #
  # get 'vendor_types/new'
  #
  # get 'vendor_types/show'
  #
  # get 'rate_cards/_form'
  #
  # get 'rate_cards/edit'
  #
  # get 'rate_cards/index'
  #
  # get 'rate_cards/new'
  #
  # get 'rate_cards/show'
  #
  # get 'vendor_type/_form'
  #
  # get 'vendor_type/edit'
  #
  # get 'vendor_type/index'
  #
  # get 'vendor_type/new'
  #
  # get 'vendor_type/show'
  #
  # get 'vendor_contract/_form'
  #
  # get 'vendor_contract/edit'
  #
  # get 'vendor_contract/index'
  #
  # get 'vendor_contract/new'
  #
  # get 'vendor_contract/show'
  #
  # get 'vendor/_form'
  #
  # get 'vendor/edit'
  #
  # get 'vendor/index'
  #
  # get 'vendor/new'
  #
  # get 'vendor/show'

  # get 'service/region'
  #
  # get 'service/name:string'
  #
  # get 'service/category:references'
  #
  # get 'service/default_commission:integer'
  #
  # get 'service/active:boolean'
  #
  # get 'regions/_form'
  #
  # get 'regions/edit'
  #
  # get 'regions/index'
  #
  # get 'regions/new'
  #
  # get 'regions/show'
  #
  # get 'cities/_form'
  #
  # get 'cities/edit'
  #
  # get 'cities/index'
  #
  # get 'cities/new'
  #
  # get 'cities/show'
  #
  # get 'city/_form'
  #
  # get 'city/edit'
  #
  # get 'city/index'
  #
  # get 'city/new'
  #
  # get 'city/show'
  #
  # get 'states/_form'
  #
  # get 'states/edit'
  #
  # get 'states/index'
  #
  # get 'states/new'
  #
  # get 'states/show'
  #
  # get 'services/_form'
  #
  # get 'services/edit'
  #
  # get 'services/index'
  #
  # get 'services/new'
  #
  # get 'services/show'

  resources :vehicles
  resources :brands
  resources :categories
  resources :services
  resources :states
  resources :cities
  resources :regions
  resources :vendors do
    collection do
      get "index2" , to:'vendors#index2'
    end
  end

  resources :vendor_contracts do
    collection do
      get "index2" , to:'vendor_contracts#index2'
    end
  end
  resources :vendor_types
  resources :rate_cards do
    collection do
      get "index2" , to:'rate_cards#index2'
    end
  end
  resources :vende_contrct_maps do
    collection do
      get "index2" , to:'vende_contrct_maps#index2'
    end
  end
  resources :vender_service_maps do
    collection do
      get "index2" , to:'vender_service_maps#index2'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  root 'application#hello'
  root 'static_pages#home'
  #  root '/layouts',layouts#application'
  #  get '/brand',  to: 'brands#new'
  get  '/brand',  to: 'brand#new'
  get '/vehicle', to:'vehicle#new'
  get '/category', to:'category#new'
  get '/service', to:'service#new'
  get '/state', to:'state#new'
  get '/city', to:'city#new'
  get '/region', to:'region#new'


  post "dynamiccitiess/:id" => "vendorform#dynamiccities"

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :vehicles, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :vendor
  has_many :regions


  
end

app/models/rate_card.rb
class RateCard < ApplicationRecord
  belongs_to :vehicle
  belongs_to :service
  belongs_to :vendor
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :city
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
  has_many :vendors
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :brand
end

app/models/vende_contrct_map.rb
class VendeContrctMap < ApplicationRecord
  belongs_to :vendor_contract
  belongs_to :category
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :region
  belongs_to :city
  belongs_to :state
  belongs_to :vendor_type
  
end

app/models/vendor_contract.rb
class VendorContract < ApplicationRecord
  belongs_to :vendor
  has_many :vende_contrct_maps



end

app/models/vendor_type.rb
class VendorType < ApplicationRecord
end

app/controllers/rate_cards_controller.rb
class RateCardsController < ApplicationController
    def new
      @rate_card = RateCard.new
      @vendors = Vendor.all.map{ |vendor| [ vendor.name, vendor.id ] }
      @vehicles = Vehicle.all.map{ |vehicle| [ vehicle.model, vehicle.id ] }
      @services = Service.all.map{ |service| [ service.name, service.id ] }
    end
    def show
      @rate_card= RateCard.find(params[:id])
    end
    def create
      @rate_card= RateCard.new(rate_card_params)
      respond_to do |format|
        if @rate_card.save
          format.html { redirect_to @rate_card, service: 'Rate Card was successfully created.' }
          format.json { render :show, status: :created, location: @rate_card }
        else
          format.html { render :new }
          format.json { render json: @rate_card.errors, status: :unprocessable_entity }
        end
      end
    end
    def update
      respond_to do |format|
          @rate_card = RateCard.find(params[:id])

        if @rate_card.update(rate_card_params)
          format.html { redirect_to @rate_card, notice: 'City was successfully updated.' }
          format.json { render :show, status: :ok, location: @rate_card }
        else
          format.html { render :edit }
          format.json { render json: @rate_card.errors, status: :unprocessable_entity }
        end
      end
    end
    def edit
        @rate_card= RateCard.find(params[:id])
        @vendors = Vendor.all.map{ |vendor| [ vendor.name, vendor.id ] }
        @vehicles = Vehicle.all.map{ |vehicle| [ vehicle.model, vehicle.id ] }
        @services = Service.all.map{ |service| [ service.name, service.id ] }
    end
    def index
      @rate_cards= RateCard.all
    end

    def index2
      params
      vendor_id = params[:vendor_id].to_i

      @rate_cards= RateCard.all
      #debugger

      @rate_cards_to_send=Array.new
      @rate_cards.each do |rc|
      #  debugger

        if rc.vendor_id == vendor_id
        #  @vendors_to_send.push(vim)
            @rate_cards_to_send << { :id => rc.id, :name => rc.vendor.name, :vehicle =>rc.vehicle.model, :service =>rc.service.name,
                                  :rate => rc.rate, :active => rc.active}
        end
      end
      render json: @rate_cards_to_send
    end

    private
    def rate_card_params
      params.require(:rate_card).permit(:vendor_id, :vehicle_id , :service_id, :rate , :active)
    end

    def set_rate_card
      @rate_card = RateCard.find(params[:id])
    end
    end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/rate_cards_helper.rb
module RateCardsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/rate_cards/_form.html.erb
<%= form_for(rate_card) do |f| %>
<% if rate_card.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(rate_card.errors.count, "error") %> prohibited this rate_card from being saved:</h2>

  <ul>
    <% rate_card.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-horizontal">
<div class="form-group">
  <div class="field">
    <%= f.label "Vendor" ,class: "control-label col-sm-2" %>
    <div class="col-sm-10">
       <%= f.select(:vendor_id, @vendors) %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= f.label "Vehicle" ,class: "control-label col-sm-2" %>
    <div class="col-sm-10">
       <%= f.select(:vehicle_id, @vehicles) %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= f.label "Service" ,class: "control-label col-sm-2" %>
    <div class="col-sm-10">
       <%= f.select(:service_id, @services) %>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label "Rate" ,class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :rate , :required => true %>
    </div>
  </div>
</div>


<div class="form-group">
  <div class="field">
    <%= f.label :active ,class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.check_box :active %>
    </div>
  </div>
</div>

<div class="form-horizontal">
  <div class="form-group">
    <div class=" actions col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
    <div>
  <% end %>

app/views/rate_cards/edit.html.erb
<h1 class="center">Update Rate Card </h1>

<%= render 'form', rate_card: @rate_card%>

<div>
  <%= link_to 'New Rate Card', new_rate_card_path%> |
  <%= link_to 'All Rate Cards', rate_cards_path%>
</div>

app/views/rate_cards/index.html.erb
<h1 class="center">Rate Card</h1>

<div class="form-horizontal center container">
  <div class="form-group ">
    <label class="col-sm-2" >Select Vendor :</label>
    <%= collection_select :rate_card , :rate_card_id, Vendor.order(:name), :id, :name, {:include_blank => false},{  prompt: "Select a city" , class: "col-sm-10"} %>
  </div>
  <div class="form-group center">
    <input type="button" id ="rate_card_index_filter_button" class="btn btn-md btn-primary center" value="Submit">
  </div>
</div>
<div style="height: 500px; overflow: auto" >
<table id="rate_card_index_table" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Rate Card id</th>
      <th>Vendor</th>
      <th>Vehicle</th>
      <th>Service</th>
      <th>rate</th>
      <th>active</th>
        <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @rate_cards.each do |rate_card|%>
    <tr>
      <td> <%=rate_card.id %></td>
      <td> <%= rate_card.vendor.name %></td>
      <td> <%= rate_card.vehicle.model %></td>
      <td> <%= rate_card.service.name %></td>
      <td> <%=rate_card.rate %></td>
      <td> <%=rate_card.active %></td>
        <td><%= link_to 'Edit', edit_rate_card_path(rate_card) %></td>
          <td><%= link_to 'Show', rate_card %></td>
      </tr>
      <% end %>

  </tbody>

</table>
</div>

<%= link_to 'New Rate Card', new_rate_card_path, class: "btn btn-md btn-primary"%>

app/views/rate_cards/new.html.erb
<h1 class="center">New Rate Card</h1>

<%= render 'form', rate_card: @rate_card %>
<div>
  <%= link_to 'All Rate Card', rate_cards_path%>
</div>

app/views/rate_cards/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-horizontal">
<p>
  <strong>Rate Card Id : </strong>
  <%= @rate_card.id %>
</p>
<p>
  <strong>Vendor : </strong>
  <%= @rate_card.vendor.name %>
</p>
<p>
  <strong>Vehicle : </strong>
  <%= @rate_card.vehicle.model %>
</p>
<p>
  <strong>Service : </strong>
  <%= @rate_card.service.name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @rate_card.rate %>
</p>

<p>
  <strong>Active:</strong>
  <%= @rate_card.active %>
</p>
</div>

<div>
  <%= link_to 'Edit', edit_rate_card_path(@rate_card) %> |
  <%= link_to 'New Rate Card', new_rate_card_path%> |
  <%= link_to 'All Rate Cards', rate_cards_path%>
</div>