config/routes.rb
Rails.application.routes.draw do








  # get 'vendor_contracts/_form'
  #
  # get 'vendor_contracts/edit'
  #
  # get 'vendor_contracts/index'
  #
  # get 'vendor_contracts/new'
  #
  # get 'vendor_contracts/show'
  #
  # get 'vendors/_form'
  #
  # get 'vendors/edit'
  #
  # get 'vendors/index'
  #
  # get 'vendors/new'
  #
  # get 'vendors/show'
  #
  # get 'vendor_types/_form'
  #
  # get 'vendor_types/edit'
  #
  # get 'vendor_types/index'
  #
  # get 'vendor_types/new'
  #
  # get 'vendor_types/show'
  #
  # get 'rate_cards/_form'
  #
  # get 'rate_cards/edit'
  #
  # get 'rate_cards/index'
  #
  # get 'rate_cards/new'
  #
  # get 'rate_cards/show'
  #
  # get 'vendor_type/_form'
  #
  # get 'vendor_type/edit'
  #
  # get 'vendor_type/index'
  #
  # get 'vendor_type/new'
  #
  # get 'vendor_type/show'
  #
  # get 'vendor_contract/_form'
  #
  # get 'vendor_contract/edit'
  #
  # get 'vendor_contract/index'
  #
  # get 'vendor_contract/new'
  #
  # get 'vendor_contract/show'
  #
  # get 'vendor/_form'
  #
  # get 'vendor/edit'
  #
  # get 'vendor/index'
  #
  # get 'vendor/new'
  #
  # get 'vendor/show'

  # get 'service/region'
  #
  # get 'service/name:string'
  #
  # get 'service/category:references'
  #
  # get 'service/default_commission:integer'
  #
  # get 'service/active:boolean'
  #
  # get 'regions/_form'
  #
  # get 'regions/edit'
  #
  # get 'regions/index'
  #
  # get 'regions/new'
  #
  # get 'regions/show'
  #
  # get 'cities/_form'
  #
  # get 'cities/edit'
  #
  # get 'cities/index'
  #
  # get 'cities/new'
  #
  # get 'cities/show'
  #
  # get 'city/_form'
  #
  # get 'city/edit'
  #
  # get 'city/index'
  #
  # get 'city/new'
  #
  # get 'city/show'
  #
  # get 'states/_form'
  #
  # get 'states/edit'
  #
  # get 'states/index'
  #
  # get 'states/new'
  #
  # get 'states/show'
  #
  # get 'services/_form'
  #
  # get 'services/edit'
  #
  # get 'services/index'
  #
  # get 'services/new'
  #
  # get 'services/show'

  resources :vehicles
  resources :brands
  resources :categories
  resources :services
  resources :states
  resources :cities
  resources :regions
  resources :vendors do
    collection do
      get "index2" , to:'vendors#index2'
    end
  end

  resources :vendor_contracts do
    collection do
      get "index2" , to:'vendor_contracts#index2'
    end
  end
  resources :vendor_types
  resources :rate_cards do
    collection do
      get "index2" , to:'rate_cards#index2'
    end
  end
  resources :vende_contrct_maps do
    collection do
      get "index2" , to:'vende_contrct_maps#index2'
    end
  end
  resources :vender_service_maps do
    collection do
      get "index2" , to:'vender_service_maps#index2'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  root 'application#hello'
  root 'static_pages#home'
  #  root '/layouts',layouts#application'
  #  get '/brand',  to: 'brands#new'
  get  '/brand',  to: 'brand#new'
  get '/vehicle', to:'vehicle#new'
  get '/category', to:'category#new'
  get '/service', to:'service#new'
  get '/state', to:'state#new'
  get '/city', to:'city#new'
  get '/region', to:'region#new'


  post "dynamiccitiess/:id" => "vendorform#dynamiccities"

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :vehicles, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :vendor
  has_many :regions


  
end

app/models/rate_card.rb
class RateCard < ApplicationRecord
  belongs_to :vehicle
  belongs_to :service
  belongs_to :vendor
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :city
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
  has_many :vendors
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :brand
end

app/models/vende_contrct_map.rb
class VendeContrctMap < ApplicationRecord
  belongs_to :vendor_contract
  belongs_to :category
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :region
  belongs_to :city
  belongs_to :state
  belongs_to :vendor_type
  
end

app/models/vendor_contract.rb
class VendorContract < ApplicationRecord
  belongs_to :vendor
  has_many :vende_contrct_maps



end

app/models/vendor_type.rb
class VendorType < ApplicationRecord
end

app/controllers/vende_contrct_maps_controller.rb
class VendeContrctMapsController < ApplicationController
  before_action :set_vende_contrct_map, only: [:show, :edit, :update, :destroy]

  # GET /vende_contrct_maps
  # GET /vende_contrct_maps.json
  def index
    @vende_contrct_maps = VendeContrctMap.all

  end
  def index2

    vendor_id = params[:vendor_id].to_i

  @vende_contrct_maps = VendeContrctMap.all
    #debugger

    @vende_contrct_maps_to_send=Array.new
    @vende_contrct_maps.each do |vcm|
    #  debugger

      if vcm.vendor_contract.vendor.id == vendor_id
      #  @vendors_to_send.push(vim)
          @vende_contrct_maps_to_send << {id: vcm.id, :name => vcm.vendor_contract.vendor.name, :category =>vcm.category.name,
                                :commission => vcm.commission, :is_inclusive => vcm.is_inclusive, :active => vcm.active}
      end
    end
    render json: @vende_contrct_maps_to_send
  end

  # GET /vende_contrct_maps/1
  # GET /vende_contrct_maps/1.json
  def show
    @vendor_contracts=VendorContract.find(params[:id])
  end

  # GET /vende_contrct_maps/new
  def new
    @vende_contrct_map = VendeContrctMap.new
    @vendor_contracts=VendorContract.all.map{ |vendor_contract| [ vendor_contract.id, vendor_contract.id ] }
      @categories=Category.all.map{ |category| [ category.name, category.id ] }
  end

  # GET /vende_contrct_maps/1/edit
  def edit
    @vendor_contracts=VendorContract.find(params[:id])
    @vendor_contracts=VendorContract.all.map{ |vendor_contract| [ vendor_contract.id, vendor_contract.id ] }
      @categories=Category.all.map{ |category| [ category.name, category.id ] }
  end



  # POST /vende_contrct_maps
  # POST /vende_contrct_maps.json
  def create
    @vende_contrct_map = VendeContrctMap.new(vende_contrct_map_params)

    respond_to do |format|
      if @vende_contrct_map.save
        format.html { redirect_to @vende_contrct_map, notice: 'Vende contrct map was successfully created.' }
        format.json { render :show, status: :created, location: @vende_contrct_map }
      else
        format.html { render :new }
        format.json { render json: @vende_contrct_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vende_contrct_maps/1
  # PATCH/PUT /vende_contrct_maps/1.json
  def update
    respond_to do |format|
      if @vende_contrct_map.update(vende_contrct_map_params)
        format.html { redirect_to @vende_contrct_map, notice: 'Vende contrct map was successfully updated.' }
        format.json { render :show, status: :ok, location: @vende_contrct_map }
      else
        format.html { render :edit }
        format.json { render json: @vende_contrct_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vende_contrct_maps/1
  # DELETE /vende_contrct_maps/1.json
  def destroy
    @vende_contrct_map.destroy
    respond_to do |format|
      format.html { redirect_to vende_contrct_maps_url, notice: 'Vende contrct map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vende_contrct_map
      @vende_contrct_map = VendeContrctMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vende_contrct_map_params
      params.require(:vende_contrct_map).permit(:id ,:vendor_contract_id, :category_id, :commission, :is_inclusive, :active)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/vende_contrct_maps_helper.rb
module VendeContrctMapsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vende_contrct_maps/_form.html.erb
<%= form_for(vende_contrct_map) do |f| %>
<% if vende_contrct_map.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(vende_contrct_map.errors.count, "error") %> prohibited this vende_contrct_map from being saved:</h2>

  <ul>
    <% vende_contrct_map.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-horizontal">
  <div class="form-group">
    <div class="field">
      <%= f.label :vendor_contract_id ,class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.select(:vendor_contract_id, @vendor_contracts) %>

      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :category_id ,class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.select(:category_id, @categories) %>

      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :commission ,class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :commission , :required => true %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :is_inclusive ,class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.check_box :is_inclusive %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :active ,class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.check_box :active %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="actions">
      <%= f.submit "Create Vendor Contract Map" %>
    </div>
  </div>
  <% end %>

app/views/vende_contrct_maps/edit.html.erb
<h1>Editing Vende Contrct Map</h1>

<%= render 'form', vende_contrct_map: @vende_contrct_map %>

<%= link_to 'Show', @vende_contrct_map %> |
<%= link_to 'Back', vende_contrct_maps_path %>

app/views/vende_contrct_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center">Vendor Contract Map</h1>
<div class="form-horizontal center container">
  <div class="form-group ">
    <label class="col-sm-2" >Select Vendor :</label>
    <%= collection_select :vende_contrct_map , :vende_contrct_map_id, Vendor.order(:name), :id, :name, {:include_blank => false},{  prompt: "Select a city" , class: "col-sm-10"} %>
  </div>
  <div class="form-group center">
    <input type="button" id ="vende_contrct_map_index_filter_button" class="btn btn-md btn-primary center" value="Submit">
  </div>
</div>
<div style="height: 500px; overflow: auto" >
<table id="vende_contrct_map_index_table" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Vendor contract</th>
      <th>Vendor Name</th>
      <th>Category</th>
      <th>Commission</th>
      <th>Is inclusive</th>
      <th>Active</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @vende_contrct_maps.each do |vende_contrct_map| %>
      <tr>
        <td><%= vende_contrct_map.vendor_contract.id %></td>
          <td><%= vende_contrct_map.vendor_contract.vendor.name %></td>
        <td><%= vende_contrct_map.category.name %></td>
        <td><%= vende_contrct_map.commission %></td>
        <td><%= vende_contrct_map.is_inclusive %></td>
        <td><%= vende_contrct_map.active %></td>
        <td><%= link_to 'Show', vende_contrct_map %></td>
        <td><%= link_to 'Edit', edit_vende_contrct_map_path(vende_contrct_map) %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Vendor Contract Map', new_vende_contrct_map_path %>

app/views/vende_contrct_maps/new.html.erb
<h1>New Vende Contrct Map</h1>

<%= render 'form', vende_contrct_map: @vende_contrct_map %>

<%= link_to 'Back', vende_contrct_maps_path %>

app/views/vende_contrct_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendor contract:</strong>
  <%= @vende_contrct_map.vendor_contract.id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vende_contrct_map.category.name %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @vende_contrct_map.commission %>
</p>

<p>
  <strong>Is Inclusive:</strong>
  <%= @vende_contrct_map.is_inclusive %>
</p>

<p>
  <strong>Active:</strong>
  <%= @vende_contrct_map.active %>
</p>

<%= link_to 'Edit', edit_vende_contrct_map_path(@vende_contrct_map) %> |
<%= link_to 'Back', vende_contrct_maps_path %>