config/routes.rb
Rails.application.routes.draw do








  # get 'vendor_contracts/_form'
  #
  # get 'vendor_contracts/edit'
  #
  # get 'vendor_contracts/index'
  #
  # get 'vendor_contracts/new'
  #
  # get 'vendor_contracts/show'
  #
  # get 'vendors/_form'
  #
  # get 'vendors/edit'
  #
  # get 'vendors/index'
  #
  # get 'vendors/new'
  #
  # get 'vendors/show'
  #
  # get 'vendor_types/_form'
  #
  # get 'vendor_types/edit'
  #
  # get 'vendor_types/index'
  #
  # get 'vendor_types/new'
  #
  # get 'vendor_types/show'
  #
  # get 'rate_cards/_form'
  #
  # get 'rate_cards/edit'
  #
  # get 'rate_cards/index'
  #
  # get 'rate_cards/new'
  #
  # get 'rate_cards/show'
  #
  # get 'vendor_type/_form'
  #
  # get 'vendor_type/edit'
  #
  # get 'vendor_type/index'
  #
  # get 'vendor_type/new'
  #
  # get 'vendor_type/show'
  #
  # get 'vendor_contract/_form'
  #
  # get 'vendor_contract/edit'
  #
  # get 'vendor_contract/index'
  #
  # get 'vendor_contract/new'
  #
  # get 'vendor_contract/show'
  #
  # get 'vendor/_form'
  #
  # get 'vendor/edit'
  #
  # get 'vendor/index'
  #
  # get 'vendor/new'
  #
  # get 'vendor/show'

  # get 'service/region'
  #
  # get 'service/name:string'
  #
  # get 'service/category:references'
  #
  # get 'service/default_commission:integer'
  #
  # get 'service/active:boolean'
  #
  # get 'regions/_form'
  #
  # get 'regions/edit'
  #
  # get 'regions/index'
  #
  # get 'regions/new'
  #
  # get 'regions/show'
  #
  # get 'cities/_form'
  #
  # get 'cities/edit'
  #
  # get 'cities/index'
  #
  # get 'cities/new'
  #
  # get 'cities/show'
  #
  # get 'city/_form'
  #
  # get 'city/edit'
  #
  # get 'city/index'
  #
  # get 'city/new'
  #
  # get 'city/show'
  #
  # get 'states/_form'
  #
  # get 'states/edit'
  #
  # get 'states/index'
  #
  # get 'states/new'
  #
  # get 'states/show'
  #
  # get 'services/_form'
  #
  # get 'services/edit'
  #
  # get 'services/index'
  #
  # get 'services/new'
  #
  # get 'services/show'

  resources :vehicles
  resources :brands
  resources :categories
  resources :services
  resources :states
  resources :cities
  resources :regions
  resources :vendors do
    collection do
      get "index2" , to:'vendors#index2'
    end
  end

  resources :vendor_contracts do
    collection do
      get "index2" , to:'vendor_contracts#index2'
    end
  end
  resources :vendor_types
  resources :rate_cards do
    collection do
      get "index2" , to:'rate_cards#index2'
    end
  end
  resources :vende_contrct_maps do
    collection do
      get "index2" , to:'vende_contrct_maps#index2'
    end
  end
  resources :vender_service_maps do
    collection do
      get "index2" , to:'vender_service_maps#index2'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  root 'application#hello'
  root 'static_pages#home'
  #  root '/layouts',layouts#application'
  #  get '/brand',  to: 'brands#new'
  get  '/brand',  to: 'brand#new'
  get '/vehicle', to:'vehicle#new'
  get '/category', to:'category#new'
  get '/service', to:'service#new'
  get '/state', to:'state#new'
  get '/city', to:'city#new'
  get '/region', to:'region#new'


  post "dynamiccitiess/:id" => "vendorform#dynamiccities"

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :vehicles, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :vendor
  has_many :regions


  
end

app/models/rate_card.rb
class RateCard < ApplicationRecord
  belongs_to :vehicle
  belongs_to :service
  belongs_to :vendor
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :city
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
  has_many :vendors
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :brand
end

app/models/vende_contrct_map.rb
class VendeContrctMap < ApplicationRecord
  belongs_to :vendor_contract
  belongs_to :category
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :region
  belongs_to :city
  belongs_to :state
  belongs_to :vendor_type
  
end

app/models/vendor_contract.rb
class VendorContract < ApplicationRecord
  belongs_to :vendor
  has_many :vende_contrct_maps



end

app/models/vendor_type.rb
class VendorType < ApplicationRecord
end

app/controllers/brands_controller.rb
  class BrandsController < ApplicationController
    def new
      @brand = Brand.new
    end
    def show
      @brand = Brand.find(params[:id])
    end

    def index
      @brands = Brand.all
    end

    #to create new brand
    # brand params are defined in private
    def create
      @brand = Brand.new(brand_params)
      respond_to do |format|
        if @brand.save
          format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
          format.json { render :show, status: :created, location: @brand }
        else
          format.html { render :new }
          format.json { render json: @brand.errors, status: :unprocessable_entity }
        end
      end
    end



    def update

      respond_to do |format|
          @brand = Brand.find(params[:id])
        if @brand.update(brand_params)
          format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
          format.json { render :show, status: :ok, location: @brand }
        else
          format.html { render :edit }
          format.json { render json: @brand.errors, status: :unprocessable_entity }
        end
      end
    end

  def edit
      @brand = Brand.find(params[:id])
  end
    private
    def brand_params
      params.require(:brand).permit( :name, :active)
    end

    def set_brand
    @brand = Brand.find(params[:id])
  end
  end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/rate_cards_helper.rb
module RateCardsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/brands/_form.html.erb
<%= form_for(brand) do |f| %>
<% if brand.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

  <ul>
    <% brand.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-horizontal">
  <div class="form-group">
    <%= f.label "Brand Name:" ,class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :name , class: "form-control" ,:required => true%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Active:" , class: "control-label col-sm-2" %>
    <div class="col-sm-1">
      <%= f.check_box :active ,class: "form-control" %>
    </div>
    <div class="col-sm-9">
    </div>
  </div>
  <div class="form-group">
    <div class=" actions col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/brands/edit.html.erb
<h1 class="center">Update Brands </h1>

<%= render 'form', brand: @brand %>

<div>
  <%= link_to 'New Brand', new_brand_path%> |
  <%= link_to 'All Brands', brands_path%>
</div>

app/views/brands/index.html.erb
<h1 class="center">Brands</h1>
<div style="height: 500px; overflow: auto" >
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Brand id</th>
      <th>Brand name</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand|%>
    <tr>
      <td> <%=brand.id %></td>
      <td> <%=brand.name %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Show', brand %></td>

      </tr>
      <% end %>

  </tbody>
</table>
</div>
<%= link_to 'New Brand', new_brand_path, class: "btn btn-md btn-primary"%>

app/views/brands/new.html.erb
<h1 class="center">New Brand</h1>

<%= render 'form', brand: @brand %>
<div>
  <%= link_to 'All Brands', brands_path%>
</div>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-horizontal">
  <div class="form-group">
  <label class = "control-label col-sm-2">Brand : </label>
  <p class = "control-label col-sm-1">  <%= @brand.name  %> </p>
</div>

  <div class="form-group">
  <label class = "control-label col-sm-2" >Active:</label>
  <p class = "control-label col-sm-1" ><%= @brand.active %></p>
</div>
<div>
  <%= link_to 'Edit', edit_brand_path(@brand) %> |
  <%= link_to 'New Brand', new_brand_path%> |
  <%= link_to 'All Brands', brands_path%>
</div>
</div>